name: Dify Workflow Scheduler

on:
  schedule:
    - cron:  "10 12 * * *"  # 每天 UTC 19:40 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  run-dify-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Dify API
        run: |
          curl -X POST 'https://api.dify.ai/v1/workflows/run' \
            --header 'Authorization: Bearer app-KrRfWw9xFxGBm39OtPzJmCKs' \
            --header 'Content-Type: application/json' \
            --data-raw '{    "inputs": {"updateDays":1},
                             "response_mode": "blocking",
                             "user": "github-action"}'
